### ISSUE TITLE
pacmod_msgs new release into Kinetic broke the pacmod build

### ISSUE THREAD

**Issue by tfoote** [astuff/astuff_sensor_msgs#51]
This release: https://github.com/ros/rosdistro/pull/23590 of 3.0.1 appears to have changed the messages in a way to break pacmod's build

The latest build: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__pacmod__ubuntu_xenial_amd64__binary/20/console
<details>
15:21:47 [ 25%] Building CXX object CMakeFiles/pacmod.dir/src/pacmod_ros_msg_handler.cpp.o
15:21:47 /usr/lib/ccache/x86_64-linux-gnu-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"pacmod\" -I/tmp/binarydeb/ros-kinetic-pacmod-2.0.2/include/pacmod -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2    -std=c++11 -o CMakeFiles/pacmod.dir/src/pacmod_ros_msg_handler.cpp.o -c /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp: In member function ‘void AS::Drivers::PACMod::PacmodTxRosMsgHandler::fillSteeringPIDRpt1(const std::shared_ptr<AS::Drivers::PACMod::PacmodTxMsg>&, pacmod_msgs::SteeringPIDRpt1*, std::__cxx11::string)’:
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:290:12: error: ‘pacmod_msgs::SteeringPIDRpt1 {aka struct pacmod_msgs::SteeringPIDRpt1_<std::allocator<void> >}’ has no member named ‘Kp’
15:21:50    new_msg->Kp = dc_parser->Kp;
15:21:50             ^
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:291:12: error: ‘pacmod_msgs::SteeringPIDRpt1 {aka struct pacmod_msgs::SteeringPIDRpt1_<std::allocator<void> >}’ has no member named ‘Ki’
15:21:50    new_msg->Ki = dc_parser->Ki;
15:21:50             ^
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:292:12: error: ‘pacmod_msgs::SteeringPIDRpt1 {aka struct pacmod_msgs::SteeringPIDRpt1_<std::allocator<void> >}’ has no member named ‘Kd’
15:21:50    new_msg->Kd = dc_parser->Kd;
15:21:50             ^
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp: In member function ‘void AS::Drivers::PACMod::PacmodTxRosMsgHandler::fillSteeringPIDRpt2(const std::shared_ptr<AS::Drivers::PACMod::PacmodTxMsg>&, pacmod_msgs::SteeringPIDRpt2*, std::__cxx11::string)’:
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:304:12: error: ‘pacmod_msgs::SteeringPIDRpt2 {aka struct pacmod_msgs::SteeringPIDRpt2_<std::allocator<void> >}’ has no member named ‘P_term’
15:21:50    new_msg->P_term = dc_parser->P_term;
15:21:50             ^
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:305:12: error: ‘pacmod_msgs::SteeringPIDRpt2 {aka struct pacmod_msgs::SteeringPIDRpt2_<std::allocator<void> >}’ has no member named ‘I_term’
15:21:50    new_msg->I_term = dc_parser->I_term;
15:21:50             ^
15:21:50 /tmp/binarydeb/ros-kinetic-pacmod-2.0.2/src/pacmod_ros_msg_handler.cpp:306:12: error: ‘pacmod_msgs::SteeringPIDRpt2 {aka struct pacmod_msgs::SteeringPIDRpt2_<std::allocator<void> >}’ has no member named ‘D_term’
15:21:50    new_msg->D_term = dc_parser->D_term;
15:21:50             ^
15:21:50 CMakeFiles/pacmod.dir/build.make:65: recipe for target 'CMakeFiles/pacmod.dir/src/pacmod_ros_msg_handler.cpp.o' failed
15:21:50 make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-pacmod-2.0.2/obj-x86_64-linux-gnu'
15:21:50 make[4]: *** [CMakeFiles/pacmod.dir/src/pacmod_ros_msg_handler.cpp.o] Error 1
15:21:50 make[3]: *** [CMakeFiles/pacmod.dir/all] Error 2
15:21:50 CMakeFiles/Makefile2:126: recipe for target 'CMakeFiles/pacmod.dir/all' failed
15:21:50 make[3]: Leaving directory '/tmp/binarydeb/ros-kinetic-pacmod-2.0.2/obj-x86_64-linux-gnu'
15:21:50 make[2]: *** [all] Error 2
15:21:50 Makefile:130: recipe for target 'all' failed
15:21:50 make[2]: Leaving directory '/tmp/binarydeb/ros-kinetic-pacmod-2.0.2/obj-x86_64-linux-gnu'
15:21:50 dh_auto_build: make -j1 returned exit code 2
15:21:50 	cd /tmp/binarydeb/ros-kinetic-pacmod-2.0.2
15:21:50 debian/rules:35: recipe for target 'override_dh_auto_build' failed
15:21:50 make[1]: Leaving directory '/tmp/binarydeb/ros-kinetic-pacmod-2.0.2'
15:21:50 make[1]: *** [override_dh_auto_build] Error 2
15:21:50 debian/rules:22: recipe for target 'build' failed
15:21:50 make: *** [build] Error 2
15:21:50 dpkg-buildpackage: error: debian/rules build gave error exit status 2
15:21:50 E: Building failed
15:21:50 Traceback (most recent call last):
15:21:50   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
15:21:50     subprocess.check_call(cmd, cwd=source_dir)
15:21:50   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
15:21:50     raise CalledProcessError(retcode, cmd)
15:21:50 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-kinetic-pacmod']' returned non-zero exit status 1
15:21:50 # END SUBSECTION
</details>

I'm [preparing for a sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-02-07/12677?u=tfoote). We can either roll this back of get a new release of pacmod in to resolve the issue. With no respond I will default to rolling back the above release before syncing.

**Comment by JWhitleyAStuff** [comment]
@tfoote - Sorry about that. We updated `pacmod3` to match the `pacmod_msgs` changes but forgot to update `pacmod`. See PR fixing this issue here: https://github.com/astuff/pacmod/pull/14. Once that's merged, I'll release to Kinetic.

**Comment by JWhitleyWork** [comment]
astuff/pacmod#14 has now been merged. ros/rosdistro#23725 is open to release the new version into Kinetic.
