### ISSUE TITLE
Do mobileye_560_660_msgs apply to MobileEye 630?

### ISSUE THREAD

**Issue by siqb** [astuff/astuff_sensor_msgs#52]
Do mobileye_560_660_msgs apply to MobileEye 630 dev kit?

https://autonomoustuff.com/product/mobileye-camera-dev-kit/

Thinking about buying it but wanna understand the information in the messages first.

**Comment by JWhitleyWork** [comment]
Yes, they do. The 660 is just the 630 without the EyeWatch display unit. The driver is available through AutonomouStuff.

**Comment by siqb** [comment]
Thanks! Are you saying the driver is not on GitHub? If not, do you have any specs/docs that explain the message format in depth? I can email you if you prefer....

**Comment by JWhitleyWork** [comment]
Due to licensing restrictions, the driver is closed-source and is only available from AutonomouStuff with the purchase of a Mobileye unit. However, if you contact sales@autonomoustuff.com, they can give you more information.
