### ISSUE TITLE
Move / rename radar_msgs

### ISSUE THREAD

**Issue by SteveMacenski** [astuff/astuff_sensor_msgs#54]
Hi,

We're working on building standardized ROS messages for radars right now and starting to finalize them. We would like to use the name `radar_msgs` since they're the generalized form of radar_msgs. However, since this repo has a package with that name, we can't release under it without conflicts. 

My understanding from talking with Josh is that these are pretty specific in nomenclature and mostly used only in Delphi drivers. 

Can we change the names to reflect that and/or migrate any use causes you have for them into our new standardized format?

**Comment by icolwell-as** [comment]
I see a few options:

1. Remove the radar_msgs package from astuff_sensor_msgs completely because delphi-specific messages already exist. This means also removing the support from the delphi drivers at the same time.
2. Rename the radar_msgs from astuff_sensor_msgs to something else and update the driver to reflect it.

Based on my current understanding of the Delphi drivers (which is limited), I'm voting for option 1 since I'm not aware of any other drivers that use the existing radar_msgs.
@JWhitleyWork, can you shed some light on this? 
- What was the original purpose of the radar_msgs packages here? to provide common msgs across Delphi ESR, SRR, and MRR drivers?
- Do any other radar drivers out there currently use these radar_msgs?

In either case, we can aim to later update the drivers to output the new standard messages now being defined.

**Comment by SteveMacenski** [comment]
> In either case, we can aim to later update the drivers to output the new standard messages now being defined.

Awesome, I think that solves our problem then. Option 1 to delete the message and migrate support to the new messages!

**Comment by JWhitleyWork** [comment]
There are a handful of personal projects out there on Github that use the existing packages. Here are the ones I would be most worried about disrupting: 

- https://github.com/usdot-fhwa-stol/carma-delphi-srr2-driver
- https://github.com/usdot-fhwa-stol/carma-platform
- https://github.com/klintan/ros2_denso_radar
- https://github.com/tudelft-iv/multi_sensor_calibration
- https://github.com/AinsteinAI/ainstein_radar
- https://github.com/KIT-MRT/mrt_cmake_modules

**Comment by SteveMacenski** [comment]
I believe all of those are in our list to file tickets with once we finish the messages. We also have Klintan involved in this process too.

**Comment by JWhitleyWork** [comment]
And yes, they were intended to support a common set of message types across all radar models.

**Comment by icolwell-as** [comment]
Thanks @JWhitleyWork 
Moving forward, what's the best order of operations to minimize disruption?

1. Notify everyone using the astuff msgs that the `radar_msgs` package will change drastically soon  and they'll need to update their drivers.
2. Finish new message types.
3. Release the new messages on top of the astuff radar_msgs. From a user perspective the `ros-<distro>-radar-msgs` package will suddenly update and be completely different. At this time we delete the radar_msgs source package here on this repo.
4. Notify everyone again that the change is complete and they can release changes to their drivers.

**Comment by SteveMacenski** [comment]
I think the best would be 
1. File tickets / notify everyone of the changes. Let them know the existing messages will be depreciated in new distros and the definitions will change slightly
2. Release the new ones, which will break people between distros, but they would have had a few weeks or months to go to have their opinions reflected in the new standard effecting future distros
3. This repo, if / when updating to noetic/foxy should just totally delete the `radar_msgs` package so that they're not released, if your plan is to use the new interfaces anyhow.

The biggest thing to me is to make sure that this existing `radar_msgs` is **not** release in the new distros (noetic, foxy). That will be the breakwater for the new messages. I will not plan on releasing the new `radar_msgs` under Eloquent and older or Melodic or older so it should not break anyone using it currently. However when they upgrade to the new distro, then they'll need to update their messages.

**Comment by icolwell-as** [comment]
Sounds good to me, I previously missed the detail about only releasing the new messages on the new distros. Certainly makes things easier!
At this point is there anything I need to do? It sounds like you've already got a list going of repos/people to notify.
I'll leave this open as a reminder to myself when we get around to a noetic release of the other message packages in this repo.

**Comment by SteveMacenski** [comment]
I think its just engaging on the radar_msgs tickets and making sure we support everything we can within reason and letting anyone know that this is open for discussion
