### ISSUE TITLE
Consider deprecating the astuff_sensor_msgs meta package

### ISSUE THREAD

**Issue by icolwell-as** [astuff/astuff_sensor_msgs#58]
It's not currently clear what benefit the `astuff_sensor_msgs` meta package serves.
Any messages in this repo will be auto-installed by the drivers since they are listed as dependencies anyway.

**Comment by JWhitleyWork** [comment]
I would tend to agree with this decision. Additionally, meta-packages aren't a thing in ROS2. You can create a package which exec-depends on a bunch of other packages but there are no special tags or uses for them like there are in ROS1.
