### ISSUE TITLE
release astuff_sensor_msgs in ROS eloquent

### ISSUE THREAD

**Issue by jbmag** [astuff/astuff_sensor_msgs#64]
Hi! Do you have any plans to release astuff_sensor_msgs for ros2 eloquent?

**Comment by dvangeyn-as** [comment]
@jbmag : We do plan to release ROS2 versions of many of our ROS drivers, however, this work is not yet scheduled. When we do ROS2, our current target will be Foxy and not Eloquent due to Foxy not going EOL until 2023 and Eloquent going EOL this November 2020.

**Comment by JWhitleyWork** [comment]
@dvangeyn-as Would it be possible to release this package into Foxy first? This should require little-to-no porting effort because the message API hasn't changed. Additionally, the AWF would like to support an initiative (that AS is also a part of) in the very near future that uses Foxy.

**Comment by icolwell-as** [comment]
Foxy:
https://github.com/ros/rosdistro/pull/26599
Eloquent:
https://github.com/ros/rosdistro/pull/26600
