### ISSUE TITLE
catkin lint reports that radar_msgs and delphi_esr_msgs are not catkin packages

### ISSUE THREAD

**Issue by kjeremy** [astuff/astuff_sensor_msgs#83]
ROS Melodic.

Given
```
find_package(catkin REQUIRED COMPONENTS
  delphi_esr_msgs radar_msgs
)
```

catkin lint is reporting 

> CMakeLists.txt(10): error: 'delphi_esr_msgs' in find_package(catkin) is not a catkin package
> CMakeLists.txt(10): error: 'radar_msgs' in find_package(catkin) is not a catkin package

**Comment by icolwell-as** [comment]
I have no experience with `catkin lint`, but are you having build problems? We've been using these two packages without issue for years.

**Comment by icolwell-as** [comment]
Closing due to age, please respond or re-open if you are still having some issue.
