### ISSUE TITLE
ibeo_msgs CMake Error

### ISSUE THREAD

**Issue by ajay1606** [astuff/astuff_sensor_msgs#94]
Hello,

Thanks for contributing ROS driver for Ibeo Lidars. 
Currently, I am trying to build a workspace using the following Ibeo packages from astuff repo.
ibeo_core
ibeo_lx
ibeo_msgs

But getting CMake error as bellow, could anyone please guide me to fix this error!

```
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
sed: can't read msg/CameraImage.msg: No such file or directory
sed: can't read msg/ContourPointSigma.msg: No such file or directory
sed: can't read msg/DeviceStatus.msg: No such file or directory
sed: can't read msg/ErrorWarning.msg: No such file or directory
sed: can't read msg/HostVehicleState2805.msg: No such file or directory
sed: can't read msg/HostVehicleState2806.msg: No such file or directory
sed: can't read msg/HostVehicleState2807.msg: No such file or directory
sed: can't read msg/IbeoDataHeader.msg: No such file or directory
sed: can't read msg/MountingPositionF.msg: No such file or directory
sed: can't read msg/Object2221.msg: No such file or directory
sed: can't read msg/Object2225.msg: No such file or directory
sed: can't read msg/Object2270.msg: No such file or directory
sed: can't read msg/Object2271.msg: No such file or directory
sed: can't read msg/Object2280.msg: No such file or directory
sed: can't read msg/ObjectData2221.msg: No such file or directory
sed: can't read msg/ObjectData2225.msg: No such file or directory
sed: can't read msg/ObjectData2270.msg: No such file or directory
sed: can't read msg/ObjectData2271.msg: No such file or directory
sed: can't read msg/ObjectData2280.msg: No such file or directory
sed: can't read msg/Point2Df.msg: No such file or directory
sed: can't read msg/Point2Di.msg: No such file or directory
sed: can't read msg/Point2Dui.msg: No such file or directory
sed: can't read msg/ResolutionInfo.msg: No such file or directory
sed: can't read msg/ScanData2202.msg: No such file or directory
sed: can't read msg/ScanData2204.msg: No such file or directory
sed: can't read msg/ScanData2205.msg: No such file or directory
sed: can't read msg/ScanData2208.msg: No such file or directory
sed: can't read msg/ScannerInfo2204.msg: No such file or directory
sed: can't read msg/ScannerInfo2205.msg: No such file or directory
sed: can't read msg/ScanPoint2202.msg: No such file or directory
sed: can't read msg/ScanPoint2204.msg: No such file or directory
sed: can't read msg/ScanPoint2205.msg: No such file or directory
sed: can't read msg/ScanPoint2208.msg: No such file or directory
sed: can't read msg/Sigma2D.msg: No such file or directory
sed: can't read msg/Size2D.msg: No such file or directory
sed: can't read msg/TrackedProperties.msg: No such file or directory
sed: can't read msg/UntrackedProperties.msg: No such file or directory
sed: can't read msg/Velocity2D.msg: No such file or directory
CMake Error at /home/ajay/ibeo_ws/build/ibeo_msgs/cmake/ibeo_msgs-genmsg.cmake:3 (message):
  Could not find messages which
  '/home/ajay/ibeo_ws/src/ibeo_msgs/msg/CameraImage.msg' depends on.  Did you
  forget to specify generate_messages(DEPENDENCIES ...)?

  Cannot locate message [Time]: unknown package [builtin_interfaces] on
  search path [{{'ibeo_msgs': ['/home/ajay/ibeo_ws/src/ibeo_msgs/msg'],
  'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}}]
Call Stack (most recent call first):
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  ibeo_msgs/CMakeLists.txt:75 (generate_messages)
```

Any response is much appreciated. 

Regards,
Ajay

**Comment by icolwell-as** [comment]
Hi @ajay1606, what version of ROS and Ubuntu are you using?

You should be able to install the ibeo_msgs package using apt as follows:
```
sudo apt install ros-$ROS_DISTRO-ibeo-msgs
```
Then you don't need to compile them from source.

**Comment by ajay1606** [comment]
@icolwell-as Thanks so much for your quick response, it's working now. Actually, in the repo https://github.com/astuff/astuff_sensor_msgs/tree/melodic/ibeo_msgs, I have downloaded the melodic branch and did catkin_make. Then got an error message as above mentioned. 

But after modifying **builtin_interfaces/Time timestamp -> time timestamp** in all the msg/*.msg files, workspace build successfully without any error message.

If there are no further issues use the ibeo_lux package with the above-mentioned modification, then will use without any installation. Or we will reinstall ibeo_msgs using sudo apt install ros-$ROS_DISTRO-ibeo-msgs as you suggested..

Appreciate your kind confirmation. 

ROS Version: Melodic
Ubuntu: 18.04

**Comment by icolwell-as** [comment]
Hi @ajay1606, I looked into this a bit more, the changes you did manually are fine, and should actually happen automatically if you are using ROS1, see this line in the CMakeLists.txt: https://github.com/astuff/astuff_sensor_msgs/blob/melodic/ibeo_msgs/CMakeLists.txt#L65

I'm not sure why it's not working for you, it worked on our CI tests, and I also just compiled the `melodic` branch on my machine (which happens to be noetic). Seems like the files are missing, or maybe have some permission problem?

Regardless, using the modified msgs as you've done is totally fine and should not have any issues.

**Comment by ajay1606** [comment]
@icolwell-as Thanks for your detailed explanation, really appreciated it. Next time when I installing it on other machine, I will try with  
`sudo apt install ros-$ROS_DISTRO-ibeo-msgs` And, if any error occurred, I will report it here.

Thanks so much for your kind assistance.
